//! `locksmith bootstrap-operator` — mint a fresh operator credential.
//!
//! Self-contained Rust-native flow that replaces the
//! `layer8-proxy-site/scripts/bootstrap-operator.py` site-side helper.
//! Useful for standalone agent-locksmith deployments (developer
//! evaluation, embedding in your own infra) where the layer8-proxy
//! bundle's sealed-creds pipeline isn't in play.
//!
//! Output:
//! - **stdout** — `operators.yaml` content (one operator entry).
//!   Pipe to a file: `locksmith bootstrap-operator > operators.yaml`.
//! - **stderr** — the cleartext wire token, printed ONCE. Save it now;
//!   it cannot be recovered from operators.yaml (only the argon2 hash
//!   is stored).
//!
//! Wire format matches what the daemon's
//! `OperatorAuthenticator::load` expects: `lkop_<public_id>.<secret>`.
//!
//! For production deploys, use the
//! `layer8-proxy-site/examples/bootstrap-operator.py` (or the local
//! site-repo equivalent) which seals the wire token at-rest via
//! systemd-creds / openssl.

use crate::client::CliError;
use agent_locksmith::argon2_helper;
use agent_locksmith::token::{StructuredToken, TokenNamespace};
use clap::Args;
use secrecy::SecretString;

#[derive(Args, Debug)]
pub struct BootstrapOperatorArgs {
    /// Operator display name written into `operators.yaml`. Used for
    /// audit attribution (`operator_name` field on admin-write rows).
    #[arg(long, default_value = "default")]
    pub name: String,

    /// Append a YAML comment header explaining the file shape.
    /// Default true; pass `--no-header` for a minimal output suitable
    /// for piping into a sealed-cred mechanism.
    #[arg(long, default_value_t = true, action = clap::ArgAction::Set)]
    pub header: bool,
}

pub fn run(args: BootstrapOperatorArgs) -> Result<(), CliError> {
    let token = StructuredToken::generate(TokenNamespace::Operator);
    let wire_token = token.wire_format();
    let public_id = token.public_id.as_str();
    let token_hash = argon2_helper::hash(&SecretString::from(token.secret.expose()))
        .map_err(|e| CliError::Usage(format!("argon2 hash failed: {e}")))?;

    if args.header {
        println!("# Locksmith operator credentials.");
        println!(
            "# Generated by `locksmith bootstrap-operator --name {}` — see",
            args.name
        );
        println!("# agent-locksmith/docs/user/concepts/agent-identity-and-acl.md");
        println!("# for the full credential lifecycle.");
        println!("#");
        println!("# Re-running bootstrap-operator OVERWRITES the cleartext wire");
        println!("# token (only the argon2 hash is stored here). Save the wire");
        println!("# token from stderr to LOCKSMITH_OP_TOKEN at install time.");
    }
    println!("operators:");
    println!("  - name: {}", args.name);
    println!("    public_id: \"{}\"", public_id);
    println!("    token_hash: \"{}\"", token_hash);

    eprintln!();
    eprintln!("✓ Operator credential minted.");
    eprintln!();
    eprintln!("  Wire token (save this NOW — cannot be recovered):");
    eprintln!();
    eprintln!("    {}", wire_token);
    eprintln!();
    eprintln!("  Install on the operator's host:");
    eprintln!();
    eprintln!("    export LOCKSMITH_OP_TOKEN='{}'", wire_token);
    eprintln!();
    eprintln!("  Or seal it via your sealed-cred mechanism (systemd-creds,");
    eprintln!("  macOS Keychain, password manager, etc.) and load before");
    eprintln!("  invoking `locksmith {{agent,model,tool,oauth,...}} ...`.");
    eprintln!();
    Ok(())
}
